'use strict';

// Pure data — no imports, no side-effects.
// Add new Eloquent / query-builder methods here; completions.js picks them up automatically.

const ELOQUENT_METHODS = [
  { name: 'all',            snippet: 'all()' },
  { name: 'get',            snippet: 'get()' },
  { name: 'find',           snippet: 'find(${1:$id})' },
  { name: 'findOrFail',     snippet: 'findOrFail(${1:$id})' },
  { name: 'findMany',       snippet: 'findMany([${1:$ids}])' },
  { name: 'first',          snippet: 'first()' },
  { name: 'firstOrFail',    snippet: 'firstOrFail()' },
  { name: 'firstOrCreate',  snippet: 'firstOrCreate([${1:}])' },
  { name: 'firstOrNew',     snippet: 'firstOrNew([${1:}])' },
  { name: 'create',         snippet: 'create([${1:}])' },
  { name: 'forceCreate',    snippet: 'forceCreate([${1:}])' },
  { name: 'updateOrCreate', snippet: 'updateOrCreate([${1:}], [${2:}])' },
  { name: 'destroy',        snippet: 'destroy(${1:$id})' },
  { name: 'truncate',       snippet: 'truncate()' },
  { name: 'query',          snippet: 'query()' },
  { name: 'where',          snippet: "where('${1:column}', ${2:'value'})" },
  { name: 'whereIn',        snippet: "whereIn('${1:column}', [${2:}])" },
  { name: 'whereNotIn',     snippet: "whereNotIn('${1:column}', [${2:}])" },
  { name: 'whereBetween',   snippet: "whereBetween('${1:column}', [${2:min}, ${3:max}])" },
  { name: 'whereNull',      snippet: "whereNull('${1:column}')" },
  { name: 'whereNotNull',   snippet: "whereNotNull('${1:column}')" },
  { name: 'with',           snippet: "with('${1:relation}')" },
  { name: 'withCount',      snippet: "withCount('${1:relation}')" },
  { name: 'has',            snippet: "has('${1:relation}')" },
  { name: 'doesntHave',     snippet: "doesntHave('${1:relation}')" },
  { name: 'whereHas',       snippet: "whereHas('${1:relation}', function (\\$q) {\n    ${2:}\n})" },
  { name: 'orderBy',        snippet: "orderBy('${1:column}', '${2:asc}')" },
  { name: 'orderByDesc',    snippet: "orderByDesc('${1:column}')" },
  { name: 'latest',         snippet: 'latest()' },
  { name: 'oldest',         snippet: 'oldest()' },
  { name: 'paginate',       snippet: 'paginate(${1:15})' },
  { name: 'simplePaginate', snippet: 'simplePaginate(${1:15})' },
  { name: 'cursorPaginate', snippet: 'cursorPaginate(${1:15})' },
  { name: 'pluck',          snippet: "pluck('${1:column}')" },
  { name: 'value',          snippet: "value('${1:column}')" },
  { name: 'count',          snippet: 'count()' },
  { name: 'sum',            snippet: "sum('${1:column}')" },
  { name: 'avg',            snippet: "avg('${1:column}')" },
  { name: 'max',            snippet: "max('${1:column}')" },
  { name: 'min',            snippet: "min('${1:column}')" },
  { name: 'exists',         snippet: 'exists()' },
  { name: 'doesntExist',    snippet: 'doesntExist()' },
  { name: 'select',         snippet: "select('${1:column}')" },
  { name: 'distinct',       snippet: 'distinct()' },
  { name: 'limit',          snippet: 'limit(${1:10})' },
  { name: 'take',           snippet: 'take(${1:10})' },
  { name: 'skip',           snippet: 'skip(${1:0})' },
  { name: 'chunk',          snippet: 'chunk(${1:100}, function (\\$items) {\n    ${2:}\n})' },
  { name: 'each',           snippet: 'each(function (\\$item) {\n    ${1:}\n})' },
  { name: 'increment',      snippet: "increment('${1:column}')" },
  { name: 'decrement',      snippet: "decrement('${1:column}')" },
  { name: 'update',         snippet: 'update([${1:}])' },
  { name: 'delete',         snippet: 'delete()' },
  { name: 'forceDelete',    snippet: 'forceDelete()' },
  { name: 'restore',        snippet: 'restore()' },
  { name: 'withTrashed',    snippet: 'withTrashed()' },
  { name: 'onlyTrashed',    snippet: 'onlyTrashed()' },
];

const CHAIN_METHODS = [
  // Terminal — return results
  { name: 'get',            snippet: 'get()' },
  { name: 'first',          snippet: 'first()' },
  { name: 'firstOrFail',    snippet: 'firstOrFail()' },
  { name: 'firstOrCreate',  snippet: 'firstOrCreate([${1:}])' },
  { name: 'firstOrNew',     snippet: 'firstOrNew([${1:}])' },
  { name: 'find',           snippet: 'find(${1:$id})' },
  { name: 'findOrFail',     snippet: 'findOrFail(${1:$id})' },
  { name: 'all',            snippet: 'all()' },
  { name: 'count',          snippet: 'count()' },
  { name: 'exists',         snippet: 'exists()' },
  { name: 'doesntExist',    snippet: 'doesntExist()' },
  { name: 'paginate',       snippet: 'paginate(${1:15})' },
  { name: 'simplePaginate', snippet: 'simplePaginate(${1:15})' },
  { name: 'cursorPaginate', snippet: 'cursorPaginate(${1:15})' },
  { name: 'pluck',          snippet: "pluck('${1:column}')" },
  { name: 'value',          snippet: "value('${1:column}')" },
  { name: 'sum',            snippet: "sum('${1:column}')" },
  { name: 'avg',            snippet: "avg('${1:column}')" },
  { name: 'max',            snippet: "max('${1:column}')" },
  { name: 'min',            snippet: "min('${1:column}')" },
  { name: 'chunk',          snippet: 'chunk(${1:100}, function (\\$items) {\n    ${2:}\n})' },
  { name: 'each',           snippet: 'each(function (\\$item) {\n    ${1:}\n})' },
  { name: 'toArray',        snippet: 'toArray()' },
  { name: 'toJson',         snippet: 'toJson()' },
  // Constraints
  { name: 'where',          snippet: "where('${1:column}', ${2:'value'})" },
  { name: 'orWhere',        snippet: "orWhere('${1:column}', ${2:'value'})" },
  { name: 'whereIn',        snippet: "whereIn('${1:column}', [${2:}])" },
  { name: 'whereNotIn',     snippet: "whereNotIn('${1:column}', [${2:}])" },
  { name: 'whereBetween',   snippet: "whereBetween('${1:column}', [${2:min}, ${3:max}])" },
  { name: 'whereNull',      snippet: "whereNull('${1:column}')" },
  { name: 'whereNotNull',   snippet: "whereNotNull('${1:column}')" },
  { name: 'whereHas',       snippet: "whereHas('${1:relation}', function (\\$q) {\n    ${2:}\n})" },
  { name: 'has',            snippet: "has('${1:relation}')" },
  { name: 'doesntHave',     snippet: "doesntHave('${1:relation}')" },
  { name: 'with',           snippet: "with('${1:relation}')" },
  { name: 'withCount',      snippet: "withCount('${1:relation}')" },
  { name: 'without',        snippet: "without('${1:relation}')" },
  { name: 'select',         snippet: "select('${1:column}')" },
  { name: 'addSelect',      snippet: "addSelect('${1:column}')" },
  { name: 'distinct',       snippet: 'distinct()' },
  { name: 'orderBy',        snippet: "orderBy('${1:column}', '${2:asc}')" },
  { name: 'orderByDesc',    snippet: "orderByDesc('${1:column}')" },
  { name: 'latest',         snippet: 'latest()' },
  { name: 'oldest',         snippet: 'oldest()' },
  { name: 'limit',          snippet: 'limit(${1:10})' },
  { name: 'take',           snippet: 'take(${1:10})' },
  { name: 'skip',           snippet: 'skip(${1:0})' },
  { name: 'offset',         snippet: 'offset(${1:0})' },
  { name: 'groupBy',        snippet: "groupBy('${1:column}')" },
  { name: 'having',         snippet: "having('${1:column}', '${2:>=}', ${3:value})" },
  // Writes
  { name: 'update',         snippet: 'update([${1:}])' },
  { name: 'delete',         snippet: 'delete()' },
  { name: 'forceDelete',    snippet: 'forceDelete()' },
  { name: 'restore',        snippet: 'restore()' },
  { name: 'increment',      snippet: "increment('${1:column}')" },
  { name: 'decrement',      snippet: "decrement('${1:column}')" },
  // Soft deletes
  { name: 'withTrashed',    snippet: 'withTrashed()' },
  { name: 'onlyTrashed',    snippet: 'onlyTrashed()' },
  // Instance methods
  { name: 'save',           snippet: 'save()' },
  { name: 'fresh',          snippet: 'fresh()' },
  { name: 'refresh',        snippet: 'refresh()' },
  { name: 'touch',          snippet: 'touch()' },
  { name: 'fill',           snippet: 'fill([${1:}])' },
  // Debug
  { name: 'dd',             snippet: 'dd()' },
  { name: 'dump',           snippet: 'dump()' },
];

module.exports = { ELOQUENT_METHODS, CHAIN_METHODS };
